BR2_TARGET_UBOOT_CUSTOM_VERSION_VALUE="2025.07"
BR2_TARGET_UBOOT_VERSION="2025.07"
BR2_TARGET_UBOOT_CONFIG_FRAGMENT_FILES += $(BR2_EXTERNAL_PANCAKE_PATH)/board/sipeed/licheepi_nano/uboot-my.fragment"
